FROM ubuntu:18.04

MAINTAINER Reginald Marr version: 0.1

RUN apt-get update && apt-get install -y \
    tmux \
    zsh \
    curl \
    wget \
    vim \
    feh \
    git \
    python \
    python3 \
    sudo \
    mesa-utils \
    unzip \
    build-essential \
	dpkg \
    cmake \
    && rm -rf /var/likb/apt/lists/*

ARG HOME=/root

WORKDIR $HOME/Downloads/gitDownloads

RUN git clone https://github.com/rizsotto/Bear.git && cd Bear \
    && mkdir -p build && cd build && cmake ../ && make all && \
    make install && make package

RUN git clone --depth 1 https://github.com/lotabout/skim.git $HOME/.skim \
    && ~/.skim/install && echo "export PATH='$PATH:$HOME/.skim/bin'" \
    | >> $HOME/.bash_aliases

RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
	&& ~/.fzf/install && echo "export PATH='$PATH:HOME/.fzf/bin'" \
    | >> $HOME/.bash_aliases

RUN apt-get update --fix-missing -y && apt-get upgrade -y

RUN apt-get install apt-utils dpkg tree -y
RUN apt-get install firefox --fix-missing -y

RUN curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb \
    && dpkg -i ripgrep_11.0.2_amd64.deb

RUN curl -LO https://github.com/sharkdp/fd/releases/download/v7.3.0/fd_7.3.0_amd64.deb \
    && dpkg -i fd_7.3.0_amd64.deb

RUN curl -LO https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb \
    && dpkg -i bat_0.12.1_amd64.deb

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

RUN apt-get install python3-pip -y && apt-get update -y

RUN apt-get install locales && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' \
    /etc/locale.gen && locale-gen

RUN cd $HOME && mkdir -p projects

COPY dotfiles/vimrc $HOME/.vimrc

COPY dotfiles/bashrc $HOME/.bashrc

COPY dotfiles/zshrc $HOME/.zshrc

COPY dotfiles/bash_aliases $HOME/.bash_aliases

COPY dotfiles/bash_scripts $HOME/.bash_scripts

RUN mkdir -p $HOME/.extra_dotfiles

COPY dotfiles/extra_dotfiles/fuzzy $HOME/.extra_dotfiles/.fuzzy

COPY dotfiles/extra_dotfiles/mx_specific $HOME/.extra_dotfiles/.mx_specific

RUN mkdir -p $HOME/profile_config/

COPY customScripts $HOME/profile_config/

RUN mkdir -p $HOME/util

COPY git-completion.sh $HOME/util/git-completion.sh

RUN "entrypoint should be used to add sk to path:

CMD ["zsh"]
