[theme]
name = "modern"
[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"
#alternating_tint_bg = "#00000000"

[icons]
name = "awesome"
[icons.overrides]
time = ""
backlight_empty = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
backlight_full = " "

#[[block]]
#block = "weather"
#format = "{temp}°C {weather}, {wind}m/s {direction}"
#service = { name = "openweathermap", api_key = "82b3c5fede9070e99419dde454a2db96", city_id = "5969785", units = "metric" }

[[block]]
block = "time"
interval = 60
format = " %a %b %d,%l:%M%p"

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = false
bitrate = true
ip = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"
display_song = false

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 3
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "nvidia_gpu"
label = "Quadro P1000"
show_memory = false
show_temperature = false
show_utilization = true
interval = 1

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time} {power}W"
