[theme]
name = "modern"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"
alternating_tint_bg = "#FFFFFFFF"

[icons]
name = "awesome"
[icons.overrides]
time = ""
backlight_empty = " "
backlight_partial1 = " "
backlight_partial2 = " "
backlight_partial3 = " "
backlight_full = " "


#[[block]]
#block = "weather"
#format = "{temp}°C {weather}, {wind}m/s {direction}"
#service = { name = "openweathermap", api_key = "82b3c5fede9070e99419dde454a2db96", city_id = "5969785", units = "metric" }

[[block]]
block = "time"
interval = 60
format = " %a %b %d,%l:%M%p"

[[block]]
block = "net"
device = "wlp2s0"
ssid = false
bitrate = true
ip = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
ssid = false
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 2
frequency = true

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{average}°C"
good = 40
idle = 50
info = 60
warning = 70

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time} {power}W"
