#
# ~/.bash_aliases
#
#check if we have thefuck installed.
#if we dont then it can be installed via
#pip3 install thefuck --user
#   if thefuck &>/dev/null; then
##       eval $(thefuck --alias fuck)
##   else
##      if [[ ! -d "/home/sw-eng" ]]; then
##           pip3 install thefuck --user
#           eval $(thefuck --alias fuck)
#      fi
#   fi

# Safeguarding aliases to confirm file changes
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias ls='ls --color=auto'
alias vi='/usr/bin/vim'
alias l='ls -Al'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'
alias rdock='make run -f ~/Projects/docker/workflow_dependency_env/ubuntu_18.04_dev_env/Makefile'


# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && \
        eval "$(dircolors -b ~/.dircolors)" || \
        eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias grep='grep -n -B 4 -A 4 --colour --exclude tags -e'

#update pkgconfig
export PATH=$HOME/.local/bin:$PATH
export PATH="$HOME/Downloads/gitDownloads/ripgrep_all-0.9.2-x86_64-unknown-linux-musl/":$PATH
export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python2.7/"
export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python3.6/"
export PKG_CONFIG_PATH='/usr/lib/x86_64-linux-gnu/pkgconfig'
export PATH=$HOME/bin:$HOME/util:$PATH
export PKG_CONFIG_PATH=$HOME/Projects/hackathon_2019/parrot_sdk/out/arsdk-native/staging/usr/lib/pkgconfig:$PKG_CONFIG_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
#this only uses the mx specific stuff if we are on an mx pc
if [ "$HOSTNAME" = ${USER}-lt ] || [ "$HOST" = ${USER}-lt ]; then
    if [ -d ${HOME/.extra_dotfiles/.mx_specific} ]; then
        source $HOME/.extra_dotfiles/.mx_specific
    else
        echo "No MX specific dotfiles found !"
    fi
fi

export HIGHLIGHT_AREA=0
#git downloads path (gpd)
export GDP=$HOME"/Downloads/gitDownloads"
export PATH="$PATH:$GDP/skim/bin"
# bash env agnostic exports

source $HOME/.extra_dotfiles/.fuzzy
alias print_files='python3 $SC/print_files.py'
function srg() {
    rg $1 -n -A3 -B3 $(print_files)
}
alias ncheck='git checkout'
alias rebase='git_rebase'
alias commit='git_commit_message'
alias fixup='git_commit_fixup'
alias cloneHome='git_clone'
alias mi='maint_ip'
alias pull='git pull -p'
alias nn='nvim'
alias asource='source ~/.bashrc;source ~/.zshrc'
alias update='sudo apt update && sudo apt upgrade -y && brew update'
alias fbit='git lg $(fzf)'
alias obd='/usr/bin/python3 ~/util/wescam-obd.py'
alias cdc='cd ~/cfgdb'
alias cdr='cd ~/Projects/workRequests/bugfixes/release/'
alias up='nmcli -p con up id Ethernet'
alias down='nmcli -p con down id Ethernet'
alias pep8='autopep8 --in-place --aggressive --aggressive'
alias today='date "+%d_%m_%Y"'
alias vnote='vi $HOME/notes/$(today).md'
alias reset='git reset HEAD --hard'

alias gfdiff='echo $(git diff --name-only)'

